version: 2

selector:
  rule: enriched_at_missing_or_stale

batch:
  size: 50
  max_concurrency: 1
  max_jobs_total: 0

timeouts:
  llm: 120

llm:
  provider: LLAMACPP
  base_url: http://127.0.0.1:8080
  model: Phi-3.5-mini-instruct-Q5_K_S.gguf
  temperature: 0.1
  max_input_chars: 4000
  max_output_tokens:
    batched: 384
timeouts:
  llm: 300    

prompts:
  # single batched prompt that returns: responsibilities, requirements, summary_tldr,
  # remote_mode, salary, skills_extra (bounded & allowlisted)
  batched: ""

language:
  detect: true
  prefer: [en, de, fr, pt, es, it]
  translate_summaries_to: ""     # not used here; keep summaries in original
  qe_min_for_llm: 0.55           # don't trust LLM extraction if MT quality is too low

guardrails:
  require_json_only: true
  skip_on_parse_error: true
  conservative_salary: true

scoring:
  coherence_penalty: 10
  rich_lists_bonus: 5

ontology:
  # keep this small to start; expand over time.
  skills_allowlist:
    - python
    - flask
    - fastapi
    - django
    - numpy
    - pandas
    - pytorch
    - tensorflow
    - sql
    - postgres
    - mysql
    - kubernetes
    - docker
    - aws
    - azure
    - gcp
    - git
    - bash
    - mlops
    - airflow
    - kafka
    - linux

  title_map:
    # regex -> normalized title
    "\\bsoftware engineer\\b": "software_engineer"
    "\\bbackend\\b": "backend_engineer"
    "\\bmachine learning engineer\\b": "machine_learning_engineer"
    "\\bdata engineer\\b": "data_engineer"
    "\\bdevops\\b": "devops_engineer"

  remote_patterns:
    - "\\bfully remote\\b"
    - "\\bremote[- ]first\\b"
    - "\\bwork from home\\b"
    - "\\banywhere\\b"
  hybrid_patterns:
    - "\\bhybrid\\b"
    - "\\b\\d{1,3}% onsite\\b"
    - "\\b\\d+ days onsite\\b"
  onsite_patterns:
    - "\\bonsite\\b"
    - "\\bon[- ]site\\b"

  # CEFR pattern examples (expand per language)
  cefr_patterns:
    C2: "\\b(native|mother tongue|C2)\\b"
    C1: "\\b(C1|business fluent|verhandlungssicher|professionnel)\\b"
    B2: "\\b(B2|fluent|fließend|avancé)\\b"
    B1: "\\b(B1|intermediate)\\b"
