skills:
  - python
  - pandas
  - numpy
  - scikit-learn
  - pytorch
  - tensorflow
  - sql
  - postgres
  - mysql
  - kafka
  - airflow
  - docker
  - kubernetes
  - aws
  - azure
  - gcp
  - git
  - bash
  - linux
  - mlops
  - fastapi
  - django
  - flask
  - time series
  - forecasting
  - anomaly detection
