skills:
  - cdl
  - cdl class a
  - cdl class b
  - hgv
  - adr
  - cpc
  - hazmat
  - tanker
  - doubles
  - triples
  - dot compliance
  - fmcsa
  - hos
  - eld
  - tachograph
  - route planning
  - dispatch
  - gps
  - load securing
  - forklift
  - pallet jack
  - otr
  - regional
  - last mile
  - delivery
