skills:
  - recruitment
  - sourcing
  - screening
  - interviewing
  - ats
  - candidate experience
  - stakeholder management
  - talent acquisition
  - employer branding
  - offer negotiation
  - onboarding
  - content moderation
  - policy enforcement
  - escalation
  - incident triage
  - trust & safety
  - risk assessment
  - shift work
  - dutch
  - english
